image: continuumio/miniconda3:latest

stages:
  - test

before_script:
  - conda -V
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda -V
  - conda update conda
  - conda -V
  - conda env create -f environment.yml
  - source activate impaej

tests36:
  stage: test
  script:
    - conda install python=3.6 -y
    - pytest -v

tests35:
  stage: test
  script:
    - conda install python=3.5 -y
    - pytest -v
