image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate impaej

tests36:
  stage: test
  script:
    - conda install python=3.6 -y
    - pytest -v

tests35:
  stage: test
  script:
    - conda install python=3.5 -y
    - pytest -v
