image: continuumio/miniconda3:latest

stages:
  - test
  - docs

before_script:
  - apt-get update -qy
  - apt-get install -y make
  - conda update conda
  - conda -V
  - conda env create -f environment.yml
  - source activate impaej

tests35:
  stage: test
  script:
    - conda install python=3.5 -y
    - pytest -v

tests36:
  stage: test
  script:
    - conda install python=3.6 -y
    - pytest -v

publishdocs:
  stage: docs
  script:
    - cd docs
    - make html
    - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
